name: chillandchat

services:
  server:
    container_name: chillandchat-backend-container
    build:
      context: ./server
      args:
        DATABASE_URL: ${DATABASE_URL}
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_PROTOCOL=${FRONTEND_PROTOCOL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

  client:
    container_name: chillandchat-client-container
    build: 
      args:
        - NEXT_PUBLIC_BACKEND_PROTOCOL=${NEXT_PUBLIC_BACKEND_PROTOCOL}
        - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
        - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}
      context: ./client
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      - NEXT_PUBLIC_BACKEND_PROTOCOL=${NEXT_PUBLIC_BACKEND_PROTOCOL}
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${NEXT_PUBLIC_BACKEND_PORT}

  database:
    image: postgres:latest
    container_name: chillandchat-database-container
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - '${DATABASE_PORT}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB} -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure