// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "src/infrastructure/persistence/schema.prisma",
  migrations: {
    path: "src/infrastructure/persistence/migrations",
  },
  datasource: {
      url: env('DATABASE_URL'),
  },
});
