POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "john_wick",
    "password": "john_wick"
}

###

POST http://localhost:3000/auth/register
content-type: application/json

{
    "username": "john_wick",
    "email": "john_wick@gmail.com",
    "password": "john_wick"
}